import type{PerformanceManifestV1}from"@atarang/contracts";
import{runtimeAssets}from"../../generated/runtime-assets";
import{fileForOpfsPath,removeOpfsDirectory}from"../../storage/opfs";
import{getBlob}from"../../storage/repositories";
import{uuidV7}from"../../storage/ids";

let exportLane:Promise<unknown>=Promise.resolve();
const download=(file:Blob,name:string)=>{const url=URL.createObjectURL(file),anchor=document.createElement("a");anchor.href=url;anchor.download=name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
export function downloadTakeAsset(take:PerformanceManifestV1,kind:"mic"|"backing"){return void(async()=>{const asset=take[kind],blob=await getBlob(asset.blobId);if(!blob)throw new Error("result_integrity_failed");download(await fileForOpfsPath(blob.opfsPath),`${kind}-${take.performanceId}.wav`)})()}
async function renderPerformanceWav(take:PerformanceManifestV1,exportId:string){const[mic,backing]=await Promise.all([getBlob(take.mic.blobId),getBlob(take.backing.blobId)]);if(!mic||!backing)throw new Error("result_integrity_failed");const worker=new Worker(runtimeAssets.recordingWorker,{type:"module",name:"atarang-wav-export"}),requestId=uuidV7(),result=await new Promise<{path:string}>((resolve,reject)=>{worker.onmessage=({data})=>{if(data.requestId!==requestId)return;if(data.type==="export/complete")resolve(data);if(data.type==="export/error")reject(new Error(data.code))};worker.onerror=()=>reject(new Error("export_failed"));worker.postMessage({type:"export/wav",requestId,performanceId:take.performanceId,exportId,sampleRate:take.sampleRate,micPath:mic.opfsPath,backingPath:backing.opfsPath,trimStartFrame:Math.round(take.edit.trimStartUs/1_000_000*take.sampleRate),trimEndFrame:Math.round(take.edit.trimEndUs/1_000_000*take.sampleRate),fadeInFrames:Math.round(take.edit.fadeInUs/1_000_000*take.sampleRate),fadeOutFrames:Math.round(take.edit.fadeOutUs/1_000_000*take.sampleRate),inputOffsetFrames:Math.round(take.inputOffsetUs/1_000_000*take.sampleRate),micGain:take.edit.micGain??.72,backingGain:take.edit.backingGain??.72})}).finally(()=>worker.terminate());return fileForOpfsPath(result.path)}
const queued=<T>(work:()=>Promise<T>)=>{const next=exportLane.then(work,work);exportLane=next.catch(()=>{});return next};
export function previewPerformanceFiles(take:PerformanceManifestV1){return queued(async()=>{const backing=await getBlob(take.backing.blobId);if(!backing)throw new Error("result_integrity_failed");return{take:await renderPerformanceWav(take,"preview"),reference:await fileForOpfsPath(backing.opfsPath),cleanup:()=>removeOpfsDirectory(`/exports/${take.performanceId}/preview`)}})}
export function exportPerformanceWav(take:PerformanceManifestV1){return queued(async()=>download(await renderPerformanceWav(take,uuidV7()),`take-${take.performanceId}.wav`))}
