import { mkdir, rename, rm } from "node:fs/promises";
import { basename, extname } from "node:path";

const outdir = "dist";
const sourceMapDir = "private-sourcemaps";
await rm(outdir, { recursive: true, force: true });
await rm(sourceMapDir, { recursive: true, force: true });
await mkdir(`${outdir}/runtime`, { recursive: true });
await mkdir(sourceMapDir, { recursive: true });

// onnxruntime-web/webgpu resolves to ort.webgpu.bundle.min.mjs, whose inlined
// Emscripten glue is the asyncify build. Feeding it the jsep binary leaves the
// module init promise pending forever, so every InferenceSession.create hangs.
//
// The glue is staged as a file as well as being inlined. Emscripten locates the
// script its pthreads load from its own import.meta.url; inlined, that is the
// worker bundle, so every spawned thread re-runs the worker instead of the glue
// and the pool never finishes starting. Loaded from its own URL it resolves
// itself, which is what makes numThreads > 1 possible at all.
const ortDist = "../../node_modules/.bun/onnxruntime-web@1.27.0/node_modules/onnxruntime-web/dist";
const stageOrtAsset = async (name: string) => {
  const bytes = new Uint8Array(await Bun.file(`${ortDist}/${name}`).arrayBuffer());
  const hash = new Bun.CryptoHasher("sha256").update(bytes).digest("hex").slice(0, 16);
  const url = `/runtime/ort-wasm-${hash}${extname(name)}`;
  await Bun.write(`${outdir}${url}`, bytes);
  return url;
};
const ortWasmUrl = await stageOrtAsset("ort-wasm-simd-threaded.asyncify.wasm");
const ortMjsUrl = await stageOrtAsset("ort-wasm-simd-threaded.asyncify.mjs");
await Bun.write("src/generated/ort-assets.ts", `// Generated by apps/web/build.ts.\nexport const ortWasmUrl = ${JSON.stringify(ortWasmUrl)};\nexport const ortMjsUrl = ${JSON.stringify(ortMjsUrl)};\n`);

// The chord front end. Two megabytes of BSD-2 weights with a recorded checksum
// (models/chords/README.md), staged content-addressed like the runtime above so
// a changed model can never be served from a stale cache.
const chordModelBytes = new Uint8Array(await Bun.file("../../models/chords/crema-chord-pitch.onnx").arrayBuffer());
const chordModelSha = new Bun.CryptoHasher("sha256").update(chordModelBytes).digest("hex");
const chordModelUrl = `/runtime/crema-chord-${chordModelSha.slice(0, 16)}.onnx`;
await Bun.write(`${outdir}${chordModelUrl}`, chordModelBytes);
await Bun.write("src/generated/chord-model.ts", `// Generated by apps/web/build.ts.\nexport const chordModelUrl = ${JSON.stringify(chordModelUrl)};\nexport const chordModelSha256 = ${JSON.stringify(chordModelSha)};\n`);

const runtimeEntries = {
  audioWorklet: "src/audio/atarang-processor.ts",
  signalsmithStretch: "src/vendor/signalsmith-stretch/SignalsmithStretch.mjs",
  ioWorker: "src/workers/io.worker.ts",
  analysisWorker: "src/workers/analysis.worker.ts",
  recordingWorker: "src/workers/recording.worker.ts",
  inferenceWorker: "src/workers/inference.worker.ts",
  serviceWorker: "src/app/service-worker.ts",
} as const;

const runtimeBuild = await Bun.build({
  entrypoints: Object.values(runtimeEntries),
  outdir: `${outdir}/runtime`,
  target: "browser",
  format: "esm",
  minify: true,
  sourcemap: "external",
  naming: "[name]-[hash].[ext]",
});
if (!runtimeBuild.success) throw new AggregateError(runtimeBuild.logs, "Runtime build failed");

const builtByStem = new Map(runtimeBuild.outputs.filter((o) => o.path.endsWith(".js")).map((o) => [basename(o.path).replace(/-[a-z0-9]+\.js$/, ""), `/runtime/${basename(o.path)}`]));
const lookup = (source: string) => {
  const stem = basename(source).replace(/\.(?:ts|mjs)$/, "");
  const url = builtByStem.get(stem);
  if (!url) throw new Error(`Missing runtime artifact for ${source}`);
  return url;
};
const generated = `// Generated by apps/web/build.ts.\nexport const runtimeAssets = ${JSON.stringify(Object.fromEntries(Object.entries(runtimeEntries).map(([key, source]) => [key, lookup(source)])), null, 2)} as const;\n`;
await Bun.write("src/generated/runtime-assets.ts", generated);

const appBuild = await Bun.build({
  entrypoints: ["src/index.html"],
  outdir,
  target: "browser",
  minify: true,
  splitting: true,
  sourcemap: "external",
  naming: { entry: "assets/[name]-[hash].[ext]", chunk: "assets/[name]-[hash].[ext]", asset: "assets/[name]-[hash].[ext]" },
});
if (!appBuild.success) throw new AggregateError(appBuild.logs, "Application build failed");

const builtHtml = appBuild.outputs.find((output) => output.path.endsWith(".html"));
if (!builtHtml) throw new Error("Application build did not emit HTML");
const html = (await Bun.file(builtHtml.path).text()).replaceAll('href="./', 'href="/assets/').replaceAll('src="./', 'src="/assets/');
await Bun.write(`${outdir}/index.html`, html);
await Bun.write(`${outdir}/manifest.webmanifest`, Bun.file("public/manifest.webmanifest"));

// Stage locally downloaded model weights so `bun run preview` can serve the
// same /models/<id>/ paths the container image publishes. Absent weights are
// normal: the app treats the model as not installed and says so.
const modelStage = "../../model-files";
if (await Bun.file(`${modelStage}/manifest.json`).exists()) {
  const staged = await Array.fromAsync(new Bun.Glob("*").scan({ cwd: modelStage }));
  for (const name of staged) await Bun.write(`${outdir}/models/htdemucs-web-onnx/${name}`, Bun.file(`${modelStage}/${name}`));
  console.log(`Staged ${staged.length} model files for local preview.`);
} else {
  console.log("No model-files/ present; run `bun models/web/download.ts` to enable browser separation locally.");
}
const publicPath = (path: string) => {
  const marker = `${outdir}/`;
  const index = path.lastIndexOf(marker);
  return `/${path.slice(index < 0 ? 0 : index + marker.length)}`;
};
const publicArtifacts = [...runtimeBuild.outputs, ...appBuild.outputs]
  .filter((output) => !output.path.endsWith(".map") && !output.path.endsWith(".html"))
  .map((output) => publicPath(output.path));
publicArtifacts.push(ortWasmUrl, ortMjsUrl);
await Bun.write(`${outdir}/precache.json`, JSON.stringify(["/index.html", "/manifest.webmanifest", ...publicArtifacts]));
for (const [name, url] of Object.entries(JSON.parse(generated.slice(generated.indexOf("{") , generated.lastIndexOf("}") + 1)) as Record<string,string>)) {
  if (!/^\/runtime\/.+-[a-z0-9]+\.js$/.test(url)) throw new Error(`${name} is not content hashed: ${url}`);
}
if (publicArtifacts.some((path) => path.endsWith(".map") || path.startsWith("/api/") || path.startsWith("/models/"))) {
  throw new Error("Precache contains a private or mutable resource");
}
if (/\.tsx?|sourceMappingURL/.test(html)) throw new Error("Production HTML exposes source entries or maps");
for (const output of [...runtimeBuild.outputs, ...appBuild.outputs].filter((item) => item.path.endsWith(".map"))) {
  await rename(output.path, `${sourceMapDir}/${basename(output.path)}`);
}
console.log(`Built ${appBuild.outputs.length} app artifacts and ${runtimeBuild.outputs.length} runtime artifacts.`);
