import { mkdir, rename, rm } from "node:fs/promises";
import { basename, extname } from "node:path";
import { DEFAULT_BACKEND_ORIGIN } from "./src/features/separation/cloudAvailability";

const outdir = "dist";
const sourceMapDir = "private-sourcemaps";
await rm(outdir, { recursive: true, force: true });
await rm(sourceMapDir, { recursive: true, force: true });
await mkdir(`${outdir}/runtime`, { recursive: true });
await mkdir(sourceMapDir, { recursive: true });

// onnxruntime-web/webgpu resolves to ort.webgpu.bundle.min.mjs, whose inlined
// Emscripten glue is the asyncify build. Feeding it the jsep binary leaves the
// module init promise pending forever, so every InferenceSession.create hangs.
//
// The glue is staged as a file as well as being inlined. Emscripten locates the
// script its pthreads load from its own import.meta.url; inlined, that is the
// worker bundle, so every spawned thread re-runs the worker instead of the glue
// and the pool never finishes starting. Loaded from its own URL it resolves
// itself, which is what makes numThreads > 1 possible at all.
const ortDist = "../../node_modules/.bun/onnxruntime-web@1.27.0/node_modules/onnxruntime-web/dist";
const stageOrtAsset = async (name: string) => {
  const bytes = new Uint8Array(await Bun.file(`${ortDist}/${name}`).arrayBuffer());
  const hash = new Bun.CryptoHasher("sha256").update(bytes).digest("hex").slice(0, 16);
  const url = `/runtime/ort-wasm-${hash}${extname(name)}`;
  await Bun.write(`${outdir}${url}`, bytes);
  return url;
};
const ortWasmUrl = await stageOrtAsset("ort-wasm-simd-threaded.asyncify.wasm");
const ortMjsUrl = await stageOrtAsset("ort-wasm-simd-threaded.asyncify.mjs");
await Bun.write("src/generated/ort-assets.ts", `// Generated by apps/web/build.ts.\nexport const ortWasmUrl = ${JSON.stringify(ortWasmUrl)};\nexport const ortMjsUrl = ${JSON.stringify(ortMjsUrl)};\n`);

// The chord front end. Two megabytes of BSD-2 weights with a recorded checksum
// (models/chords/README.md), staged content-addressed like the runtime above so
// a changed model can never be served from a stale cache.
const chordModelBytes = new Uint8Array(await Bun.file("../../models/chords/crema-chord.onnx").arrayBuffer());
const chordModelSha = new Bun.CryptoHasher("sha256").update(chordModelBytes).digest("hex");
const chordModelUrl = `/runtime/crema-chord-${chordModelSha.slice(0, 16)}.onnx`;
await Bun.write(`${outdir}${chordModelUrl}`, chordModelBytes);
// The tag head's class order is exported from the checkpoint's own encoder, not
// written down by hand — nothing in the ONNX graph records which chord each of
// the 170 outputs means, and guessing the order transposes every chord silently.
// Inlined rather than fetched: 1.6 KB against a second request that can fail.
const chordVocabulary = await Bun.file("../../models/chords/crema-chord-vocabulary.json").json() as string[];
await Bun.write("src/generated/chord-model.ts", `// Generated by apps/web/build.ts.\nexport const chordModelUrl = ${JSON.stringify(chordModelUrl)};\nexport const chordModelSha256 = ${JSON.stringify(chordModelSha)};\nexport const chordVocabulary = ${JSON.stringify(chordVocabulary)} as const;\n`);

// What the About section calls the build. Copied out here rather than imported
// in the app, so the client carries one string and not the whole manifest.
const { version } = await Bun.file("package.json").json() as { version: string };
const commit = Bun.spawnSync(["git", "rev-parse", "--short=7", "HEAD"]).stdout.toString().trim();
const dirty = Bun.spawnSync(["git", "status", "--porcelain", "--untracked-files=all", "--", ".", ":(exclude)src/generated/app-version.ts"]).stdout.toString().trim() ? "-dirty" : "";
await Bun.write("src/generated/app-version.ts", `// Generated by apps/web/build.ts.\nexport const appVersion = ${JSON.stringify(`${version} [${commit}${dirty}]`)};\n`);

// Where the app looks for a backend, substituted into the bundle rather than
// written to src/generated/: the value depends on the environment, so a
// committed copy would change under whoever ran the last command with a
// different one — which is exactly how an e2e run comes to rewrite a source
// file. The default lives beside the code that uses it.
//
// Set ATARANG_BACKEND_URL to aim a dev server or a one-off build elsewhere, or
// to empty for a build that only ever uses the page's own origin. dev.ts spawns
// this script with the environment it inherited, so the override reaches it too.
const configuredBackend = (Bun.env.ATARANG_BACKEND_URL ?? DEFAULT_BACKEND_ORIGIN).trim();
let backendOrigin = "";
if (configuredBackend) {
  let url: URL;
  try { url = new URL(configuredBackend); } catch { throw new Error(`ATARANG_BACKEND_URL is not a valid URL: ${configuredBackend}`); }
  if (url.protocol !== "http:" && url.protocol !== "https:") throw new Error(`ATARANG_BACKEND_URL must be http(s): ${configuredBackend}`);
  backendOrigin = url.origin;
}
// Without this React resolves its development entry: the DevTools banner, the
// dev-only warning machinery, and StrictMode's double-invoked effects all ship
// to production — the last of which had the tuner opening two microphone
// streams and stopping one of them.
const define = {
  __ATARANG_BACKEND_ORIGIN__: JSON.stringify(backendOrigin),
  "process.env.NODE_ENV": JSON.stringify("production"),
};

const runtimeEntries = {
  audioWorklet: "src/audio/atarang-processor.ts",
  signalsmithStretch: "src/vendor/signalsmith-stretch/SignalsmithStretch.mjs",
  ioWorker: "src/workers/io.worker.ts",
  analysisWorker: "src/workers/analysis.worker.ts",
  recordingWorker: "src/workers/recording.worker.ts",
  inferenceWorker: "src/workers/inference.worker.ts",
} as const;

// Built with the other runtime entries but deliberately not one of them: a
// worker's scope is the directory it is served from, so a service worker under
// /runtime/ only ever controlled /runtime/ — the navigation fallback and the
// whole precache never applied to a single page. A content-hashed name is the
// second half of the same problem: `registration.update()` re-fetches the script
// by URL, and the next build had already renamed it, so an open tab could never
// discover that a newer build exists.
const serviceWorkerSource = "src/app/service-worker.ts";
const serviceWorkerUrl = "/service-worker.js";

const runtimeBuild = await Bun.build({
  entrypoints: [...Object.values(runtimeEntries), serviceWorkerSource],
  outdir: `${outdir}/runtime`,
  target: "browser",
  format: "esm",
  minify: true,
  sourcemap: "external",
  naming: "[name]-[hash].[ext]",
  define,
});
if (!runtimeBuild.success) throw new AggregateError(runtimeBuild.logs, "Runtime build failed");

const builtByStem = new Map(runtimeBuild.outputs.filter((o) => o.path.endsWith(".js")).map((o) => [basename(o.path).replace(/-[a-z0-9]+\.js$/, ""), `/runtime/${basename(o.path)}`]));
const lookup = (source: string) => {
  const stem = basename(source).replace(/\.(?:ts|mjs)$/, "");
  const url = builtByStem.get(stem);
  if (!url) throw new Error(`Missing runtime artifact for ${source}`);
  return url;
};
const generated = `// Generated by apps/web/build.ts.\nexport const runtimeAssets = ${JSON.stringify(Object.fromEntries(Object.entries(runtimeEntries).map(([key, source]) => [key, lookup(source)])), null, 2)} as const;\n`;
await Bun.write("src/generated/runtime-assets.ts", generated);

// Moved rather than copied: a second, hashed copy under /runtime/ would be
// precached and immutable, which is the state this whole arrangement exists to
// avoid. `main.tsx` registers the root path literally, so nothing generated
// needs to name it.
const serviceWorkerBuilt = runtimeBuild.outputs.find((output) => basename(output.path).startsWith("service-worker-") && output.path.endsWith(".js"));
if (!serviceWorkerBuilt) throw new Error("Runtime build did not emit a service worker");
await Bun.write(`${outdir}${serviceWorkerUrl}`, Bun.file(serviceWorkerBuilt.path));
await rm(serviceWorkerBuilt.path);

const appBuild = await Bun.build({
  entrypoints: ["src/index.html"],
  outdir,
  target: "browser",
  minify: true,
  splitting: true,
  sourcemap: "external",
  naming: { entry: "assets/[name]-[hash].[ext]", chunk: "assets/[name]-[hash].[ext]", asset: "assets/[name]-[hash].[ext]" },
  define,
});
if (!appBuild.success) throw new AggregateError(appBuild.logs, "Application build failed");

const builtHtml = appBuild.outputs.find((output) => output.path.endsWith(".html"));
if (!builtHtml) throw new Error("Application build did not emit HTML");
const html = (await Bun.file(builtHtml.path).text()).replaceAll('href="./', 'href="/assets/').replaceAll('src="./', 'src="/assets/');
await Bun.write(`${outdir}/index.html`, html);

// The headers a static host must send, in the format Cloudflare Workers, Pages
// and Netlify all read. Without cross-origin isolation `crossOriginIsolated` is
// false and separation, four-stem playback, metronome, count-in and recording
// all refuse to start, so a static deployment that forgets these looks broken
// rather than unconfigured. Compose sends the same set from its Caddyfile.
//
// connect-src is written from the same constant the app probes, so the policy
// and the code can never disagree about which backend is allowed.
//
// Cache-Control is set only where the filename carries a content hash, matching
// the Caddyfile's immutable rule exactly. /models/ is deliberately not on that
// list: the weights and their manifest live at fixed paths, so marking them
// immutable would pin every returning browser to one model version for a year.
// One header named by two matching rules is combined rather than replaced, so
// the prefixes must not overlap.
const csp = [
  "default-src 'self'",
  "script-src 'self' 'wasm-unsafe-eval'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "media-src 'self' blob:",
  `connect-src 'self' https://lrclib.net${backendOrigin ? ` ${backendOrigin}` : ""}`,
  "worker-src 'self' blob:",
  "object-src 'none'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
].join("; ");
await Bun.write(`${outdir}/_headers`, [
  "/*",
  "  Cross-Origin-Opener-Policy: same-origin",
  "  Cross-Origin-Embedder-Policy: require-corp",
  "  Cross-Origin-Resource-Policy: same-origin",
  "  X-Content-Type-Options: nosniff",
  "  Referrer-Policy: no-referrer",
  "  Permissions-Policy: camera=(), geolocation=(), payment=(), usb=()",
  `  Content-Security-Policy: ${csp}`,
  "",
  "/assets/*",
  "  Cache-Control: public, max-age=31536000, immutable",
  "",
  "/runtime/*",
  "  Cache-Control: public, max-age=31536000, immutable",
  "",
  // The one file that must never be pinned: it is how an installed copy finds
  // out that everything else has been replaced.
  serviceWorkerUrl,
  "  Cache-Control: no-cache",
  "",
].join("\n"));

// Installed-app icons, copied rather than generated: they are rasterised from
// src/assets/icon.svg once by hand, so no build step needs an SVG renderer.
// Root paths because the manifest is content-hashed into /assets/ and iOS looks
// for /apple-touch-icon.png with no markup at all.
for (const name of ["icon-192.png", "icon-512.png", "apple-touch-icon.png"]) {
  const source = Bun.file(`src/assets/${name}`);
  if (!(await source.exists())) throw new Error(`Missing app icon src/assets/${name}`);
  await Bun.write(`${outdir}/${name}`, source);
}

// Include the checked-in model weights at the same /models/<id>/ paths the
// container image publishes.
const modelStage = "../../model-files";
const staged = await Array.fromAsync(new Bun.Glob("*").scan({ cwd: modelStage }));
for (const name of staged) await Bun.write(`${outdir}/models/htdemucs-web-onnx/${name}`, Bun.file(`${modelStage}/${name}`));
console.log(`Staged ${staged.length} model files.`);
const publicPath = (path: string) => {
  const marker = `${outdir}/`;
  const index = path.lastIndexOf(marker);
  return `/${path.slice(index < 0 ? 0 : index + marker.length)}`;
};
// The service worker is left out: a worker that serves itself from its own
// precache is a worker that can never be replaced.
const publicArtifacts = [...runtimeBuild.outputs, ...appBuild.outputs]
  .filter((output) => !output.path.endsWith(".map") && !output.path.endsWith(".html") && output.path !== serviceWorkerBuilt.path)
  .map((output) => publicPath(output.path));
publicArtifacts.push(ortWasmUrl, ortMjsUrl);
await Bun.write(`${outdir}/precache.json`, JSON.stringify(["/index.html", ...publicArtifacts]));
for (const [name, url] of Object.entries(JSON.parse(generated.slice(generated.indexOf("{") , generated.lastIndexOf("}") + 1)) as Record<string,string>)) {
  if (!/^\/runtime\/.+-[a-z0-9]+\.js$/.test(url)) throw new Error(`${name} is not content hashed: ${url}`);
}
if (publicArtifacts.some((path) => path.endsWith(".map") || path.startsWith("/api/") || path.startsWith("/models/"))) {
  throw new Error("Precache contains a private or mutable resource");
}
if (/\.tsx?|sourceMappingURL/.test(html)) throw new Error("Production HTML exposes source entries or maps");
for (const output of [...runtimeBuild.outputs, ...appBuild.outputs].filter((item) => item.path.endsWith(".map"))) {
  await rename(output.path, `${sourceMapDir}/${basename(output.path)}`);
}
console.log(`Built ${appBuild.outputs.length} app artifacts and ${runtimeBuild.outputs.length} runtime artifacts.`);
