import type { ChartLineV1,ChartSegmentV1,UserChartV1 } from "@atarang/contracts";

const SHARPS=["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"] as const,FLATS=["C","Db","D","Eb","E","F","Gb","G","Ab","A","Bb","B"] as const,NATURAL:Record<string,number>={C:0,D:2,E:4,F:5,G:7,A:9,B:11};
export interface ParsedChord {root:string;quality:string;bass?:string;raw:string}

export function parseChord(value:string):ParsedChord|null{const raw=value.trim().replaceAll("♯","#").replaceAll("♭","b"),match=raw.match(/^([A-Ga-g])([#b]?)([^/]*?)(?:\/([A-Ga-g])([#b]?))?$/);if(!match)return null;const note=(letter:string,accidental:string)=>letter.toUpperCase()+accidental;let quality=match[3]!.trim().replace(/^min/i,"m").replace(/^major/i,"maj").replace(/^minor/i,"m");const result:ParsedChord={root:note(match[1]!,match[2]!),quality,raw};if(match[4])result.bass=note(match[4],match[5]!);return result}
function noteIndex(note:string){const parsed=note.match(/^([A-G])([#b]?)$/);if(!parsed)return null;return(NATURAL[parsed[1]!]!+(parsed[2]==="#"?1:parsed[2]==="b"?-1:0)+12)%12}
function transposeNote(note:string,semitones:number,preferFlats:boolean){const index=noteIndex(note);return index===null?note:(preferFlats?FLATS:SHARPS)[(index+semitones+120)%12]!}
export function simplifyChord(value:string){const chord=parseChord(value);if(!chord)return value;let quality=chord.quality;if(/^maj/i.test(quality))quality="";else if(/^m(?!aj)/i.test(quality))quality="m";else if(/^dim/i.test(quality))quality="dim";else if(/^aug|^\+/i.test(quality))quality="aug";else if(/^sus2/i.test(quality))quality="sus2";else if(/^sus/i.test(quality))quality="sus4";else quality="";return `${chord.root}${quality}${chord.bass?`/${chord.bass}`:""}`}
export function transposeChord(value:string,semitones:number,simplify=false){const chord=parseChord(value);if(!chord)return value;const preferFlats=chord.root.includes("b")||chord.bass?.includes("b")===true,quality=simplify?simplifyChord(`${chord.root}${chord.quality}`).slice(chord.root.length):chord.quality;return`${transposeNote(chord.root,semitones,preferFlats)}${quality}${chord.bass?`/${transposeNote(chord.bass,semitones,preferFlats)}`:""}`}

function parseSegments(line:string):ChartSegmentV1[]{const segments:ChartSegmentV1[]=[];let cursor=0,chord:string|undefined;for(const match of line.matchAll(/\[([^\]]+)]/g)){const text=line.slice(cursor,match.index);if(text||chord!==undefined){const segment:ChartSegmentV1={text};if(chord!==undefined)segment.chord=chord;segments.push(segment)}chord=match[1]!.trim();cursor=match.index!+match[0].length}const tail=line.slice(cursor);if(tail||chord!==undefined){const segment:ChartSegmentV1={text:tail};if(chord!==undefined)segment.chord=chord;segments.push(segment)}return segments.length?segments:[{text:line}]}
export function parseChordPro(text:string,originalId:string,chartId:string,fallbackTitle="Untitled chart",now=new Date().toISOString()):UserChartV1{let title=fallbackTitle,artist="",declaredKey:string|undefined,section:string|undefined;const lines:ChartLineV1[]=[];for(const raw of text.replaceAll("\r","").split("\n")){const directive=raw.match(/^\{([^:}]+)(?::\s*([^}]*))?}$/);if(directive){const key=directive[1]!.toLowerCase().replaceAll("_"," "),value=directive[2]?.trim()??"";if(key==="title"||key==="t")title=value;if(key==="artist"||key==="subtitle"||key==="st")artist=value;if(key==="key")declaredKey=value;if(key==="start of chorus"||key==="soc")section=value||"Chorus";if(key==="start of verse"||key==="sov")section=value||"Verse";if(key==="comment"||key==="c")section=value;continue}if(!raw.trim())continue;const line:ChartLineV1={id:`${chartId}:line:${lines.length}`,segments:parseSegments(raw)};if(section){line.section=section;section=undefined}lines.push(line)}const chart:UserChartV1={schema:"atarang.chart/1",chartId,originalId,revision:0,title,artist,transposeSemitones:0,capo:0,simplify:false,lines,updatedAt:now};if(declaredKey)chart.declaredKey=declaredKey;return chart}
export function exportChordPro(chart:UserChartV1){const output=[`{title: ${chart.title}}`];if(chart.artist)output.push(`{artist: ${chart.artist}}`);if(chart.declaredKey)output.push(`{key: ${chart.declaredKey}}`);for(const line of chart.lines){if(line.section)output.push(`{comment: ${line.section}}`);output.push(line.segments.map(segment=>`${segment.chord?`[${segment.chord}]`:""}${segment.text}`).join(""))}return`${output.join("\n")}\n`}
