import {describe,expect,test} from "bun:test";
import {amplitudeToDb,cqtBands,cqtFrame,CQT_BINS,DB_FLOOR} from "./cqt";
import fixture from "./cqt-fixture.json";

describe("constant-Q input",()=>{
  // Generated by the same triangular definition in Python (models/chords), so a
  // drift between the two implementations shows up here rather than as chords
  // that are quietly worse.
  test("matches the Python reference bin for bin",()=>{
    for(const harmonic of [1,2] as const){
      const bands=cqtBands(fixture.sampleRate,fixture.fftSize,harmonic);
      const actual=cqtFrame(fixture.magnitudes,bands);
      const expected=harmonic===1?fixture.harmonic1:fixture.harmonic2;
      expect(actual.length).toBe(CQT_BINS);
      let worst=0;
      for(let bin=0;bin<CQT_BINS;bin++)worst=Math.max(worst,Math.abs(actual[bin]!-expected[bin]!));
      expect(worst).toBeLessThan(1e-6);
    }
  });

  test("puts a tone in the bin that names it",()=>{
    const sampleRate=44_100,fftSize=8192,magnitudes=new Float64Array(fftSize/2+1);
    magnitudes[Math.round(440/(sampleRate/fftSize))]=1;
    const values=cqtFrame(magnitudes,cqtBands(sampleRate,fftSize,1));
    // A4 is 45 semitones above C1, and every semitone is three bins.
    const loudest=values.indexOf(Math.max(...values));
    expect(Math.abs(loudest-45*3)).toBeLessThanOrEqual(1);
  });

  test("decibels are relative to the loudest bin in the song, floored 80 below",()=>{
    const frames=[Float32Array.from([1,0.1,0]),Float32Array.from([0.5,1e-9,2])];
    amplitudeToDb(frames);
    expect(frames[1]![2]).toBeCloseTo(0,6);
    expect(frames[0]![0]).toBeCloseTo(20*Math.log10(0.5),4);
    expect(frames[0]![2]).toBe(DB_FLOOR);
  });
});
