import {describe,expect,test} from "bun:test";
import {beatGridErrors,chordAnalysisErrors,lyricsDocumentErrors,modelArtifactManifestErrors,performanceManifestErrors,practiceStateErrors,separationManifestErrors,userChartErrors,type BeatGridV1,type ChordAnalysisV1,type LyricsDocumentV1,type ModelArtifactManifestV1,type PerformanceManifestV1,type PracticeStateV1,type SeparationManifestV1,type UserChartV1} from "./types";
const sha="a".repeat(64); const id="019febeb-fc5b-7606-87a7-cb01671988d3";
const manifest:SeparationManifestV1={schema:"atarang.separation/1",separationId:id,original:{originalId:id,contentSha256:sha,sourceMediaType:"audio/wav",sampleRate:44100,channels:2,durationFrames:44100},model:{modelId:"htdemucs-4stem",artifactVersion:"test",artifactSha256:sha,upstream:"facebookresearch/demucs htdemucs",license:"MIT"},pipeline:{implementation:"server-pytorch",implementationVersion:"test",decodeVersion:"test",preprocessVersion:"test",segmentFrames:343980,overlapFrames:85995,shifts:1,postprocessVersion:"test"},stems:(["vocals","drums","bass","other"] as const).map(kind=>({kind,blobId:`sha256:${sha}`,sampleRate:44100,channels:2,durationFrames:44100,variants:[{encoding:"pcm-f32le-wav",mediaType:"audio/wav",byteLength:10,sha256:sha}]})) as SeparationManifestV1["stems"],provenance:{mode:"local",createdAt:"2026-08-10T00:00:00.000Z"}};
describe("SeparationManifestV1",()=>{test("accepts the canonical four-stem order",()=>expect(separationManifestErrors(manifest)).toEqual([]));test("rejects duplicate or reordered stems",()=>{const invalid=structuredClone(manifest);[invalid.stems[0],invalid.stems[1]]=[invalid.stems[1],invalid.stems[0]];expect(separationManifestErrors(invalid)).toContain("stem 0 must be vocals")})});
describe("PracticeStateV1",()=>{const practice:PracticeStateV1={schema:"atarang.practice/1",originalId:id,revision:1,sourceTimeUs:2_000_000,target:"vocals",loop:{enabled:true,startTimeUs:1_000_000,endTimeUs:2_000_000},speed:.8,pitchSemitones:0,repetitions:4,pauseSeconds:2,countIn:2,metronome:true,stemGainDb:{vocals:0,drums:0,bass:-2.5,other:-4},updatedAt:"2026-08-10T00:00:00.000Z"};test("accepts bounded source-time practice state",()=>expect(practiceStateErrors(practice)).toEqual([]));test("rejects loops shorter than half a second",()=>expect(practiceStateErrors({...practice,loop:{enabled:true,startTimeUs:1_000_000,endTimeUs:1_499_999}})).toContain("loop boundaries must be at least 0.5 seconds apart"));
  // Sections and the speed ramp arrived after the first release, so a document
  // written without them has to keep reading — that is the rollback window.
  test("reads a document written before sections and the speed ramp",()=>expect(practiceStateErrors({...practice,sections:undefined,speedRampPercent:undefined})).toEqual([]));
  test("accepts named passages and a ramp inside its range",()=>expect(practiceStateErrors({...practice,sections:[{id:"01",name:"Chorus",startTimeUs:0,endTimeUs:8_000_000}],speedRampPercent:5})).toEqual([]));
  test("rejects an unnamed passage",()=>expect(practiceStateErrors({...practice,sections:[{id:"01",name:"  ",startTimeUs:0,endTimeUs:8_000_000}]})).toContain("sections must be named passages at least 0.5 seconds long"));
  test("rejects a passage too short to loop",()=>expect(practiceStateErrors({...practice,sections:[{id:"01",name:"Blip",startTimeUs:0,endTimeUs:400_000}]})).toContain("sections must be named passages at least 0.5 seconds long"));
  test("rejects a ramp that would run away",()=>expect(practiceStateErrors({...practice,speedRampPercent:80})).toContain("speedRampPercent must be between 0 and 25"))});
describe("LyricsDocumentV1",()=>{const lyrics:LyricsDocumentV1={schema:"atarang.lyrics/1",originalId:id,revision:1,offsetUs:0,lines:[{id:"line-1",text:"Hello",startTimeUs:1_000_000,endTimeUs:2_000_000,source:"lrc",confidence:1,words:[]}],updatedAt:"2026-08-10T00:00:00.000Z"};test("accepts timed lyric lines",()=>expect(lyricsDocumentErrors(lyrics)).toEqual([]));test("rejects reversed intervals",()=>expect(lyricsDocumentErrors({...lyrics,lines:[{...lyrics.lines[0]!,endTimeUs:500_000}]})).toContain("line 0 end is invalid"))});
describe("UserChartV1",()=>{const chart:UserChartV1={schema:"atarang.chart/1",chartId:id,originalId:id,revision:1,title:"Song",artist:"Artist",transposeSemitones:0,capo:0,simplify:false,lines:[{id:"line-1",segments:[{chord:"Am",text:"Hello"}]}],updatedAt:"2026-08-10T00:00:00.000Z"};test("accepts independent user chart state",()=>expect(userChartErrors(chart)).toEqual([]));test("bounds capo",()=>expect(userChartErrors({...chart,capo:13})).toContain("capo is invalid"))});
describe("BeatGridV1",()=>{const grid:BeatGridV1={schema:"atarang.beats/1",originalId:id,revision:0,algorithmVersion:"atarang-spectral-flux/1",bpm:120,reliability:.9,reliable:true,userEdited:false,beats:[{timeUs:0,beatInBar:1,downbeat:true},{timeUs:500_000,beatInBar:2,downbeat:false}],updatedAt:"2026-08-10T00:00:00.000Z"};test("accepts an ordered four-beat grid",()=>expect(beatGridErrors(grid)).toEqual([]));test("rejects inconsistent downbeats",()=>expect(beatGridErrors({...grid,beats:[{timeUs:0,beatInBar:1,downbeat:false}]})).toContain("beats are invalid"))});
describe("ChordAnalysisV1",()=>{const analysis:ChordAnalysisV1={schema:"atarang.chords/1",originalId:id,revision:0,algorithmVersion:"atarang-chroma/2",key:"C",confidence:.8,segments:[{startTimeUs:0,endTimeUs:1_000_000,chord:"C",confidence:.9}],updatedAt:"2026-08-10T00:00:00.000Z"};test("accepts source-time chord segments",()=>expect(chordAnalysisErrors(analysis)).toEqual([]));test("rejects reversed segments",()=>expect(chordAnalysisErrors({...analysis,segments:[{...analysis.segments[0]!,endTimeUs:0}]})).toContain("chord segments are invalid"))});
describe("PerformanceManifestV1",()=>{const asset={blobId:`sha256:${sha}`,sha256:sha,byteLength:44144,mediaType:"audio/wav" as const},take:PerformanceManifestV1={schema:"atarang.performance/1",performanceId:id,originalId:id,revision:0,startedAt:"2026-08-10T00:00:00.000Z",endedAt:"2026-08-10T00:00:01.000Z",sampleRate:44100,channels:2,durationFrames:44100,mic:asset,backing:asset,inputOffsetUs:0,deviceSettings:{echoCancellation:false},edit:{trimStartUs:0,trimEndUs:1_000_000,fadeInUs:0,fadeOutUs:0},updatedAt:"2026-08-10T00:00:01.000Z"};test("accepts aligned dry mic and backing assets",()=>expect(performanceManifestErrors(take)).toEqual([]));test("rejects implausible trim metadata",()=>expect(performanceManifestErrors({...take,edit:{...take.edit,trimEndUs:2_000_000}})).toContain("edit metadata is invalid"))});
describe("ModelArtifactManifestV1",()=>{const pieces=Array.from({length:21},(_,order)=>({name:`piece-${order}.onnx`,url:`/models/piece-${order}.onnx`,order,byteLength:10,sha256:sha,inputs:order?[`boundary-${order-1}`]:["mix","mag"],outputs:order===18?["freq",`boundary-${order}`]:order===20?["time"]:[`boundary-${order}`]})),model:ModelArtifactManifestV1={schema:"atarang.model/1",modelArtifactId:id,modelId:"htdemucs-web-onnx",artifactVersion:"test",artifactSha256:sha,ortVersion:"1.27.0",totalBytes:210,pieces,graphs:{inputs:["mix","mag"],outputs:{freq:"freq",time:"time"},stftOutsideGraph:true},upstream:"monteslu/htdemucs-web-onnx",license:"MIT",createdAt:"2026-08-10T00:00:00.000Z"};test("accepts graph outputs produced by different pieces",()=>expect(modelArtifactManifestErrors(model)).toEqual([]));test("rejects remote model URLs",()=>expect(modelArtifactManifestErrors({...model,pieces:model.pieces.map((piece,index)=>index?piece:{...piece,url:"https://example.com/model.onnx"})})).toContain("piece 0 is invalid"));test("rejects a graph input that was not produced by an earlier piece",()=>expect(modelArtifactManifestErrors({...model,pieces:model.pieces.map((piece,index)=>index===10?{...piece,inputs:["future"]}:piece)})).toContain("piece 10 is invalid"))});
test("the bundled browser model manifest satisfies the reviewed contract",async()=>{const value:unknown=await Bun.file(new URL("../../../models/web/manifest.json",import.meta.url)).json();expect(modelArtifactManifestErrors(value)).toEqual([])});
