import{expect,test}from"@playwright/test";

function silentWav(frames=4_410){const buffer=Buffer.alloc(44+frames*4),view=new DataView(buffer.buffer,buffer.byteOffset,buffer.byteLength),text=(offset:number,value:string)=>buffer.write(value,offset,"ascii");text(0,"RIFF");view.setUint32(4,36+frames*4,true);text(8,"WAVE");text(12,"fmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,2,true);view.setUint32(24,44_100,true);view.setUint32(28,176_400,true);view.setUint16(32,4,true);view.setUint16(34,16,true);text(36,"data");view.setUint32(40,frames*4,true);return buffer}

test("production shell is isolated and the bundled demo really plays",async({page,request})=>{const response=await request.get("/");expect(response.ok()).toBeTruthy();expect(response.headers()["cross-origin-opener-policy"]).toBe("same-origin");expect(response.headers()["cross-origin-embedder-policy"]).toBe("require-corp");const errors:string[]=[];page.on("console",message=>{if(message.type()==="error")errors.push(message.text())});page.on("pageerror",error=>errors.push(error.message));await page.goto("/studio");await expect(page.getByRole("link",{name:"Atarang Studio home"})).toBeVisible();await expect(page.getByRole("navigation",{name:"Primary navigation"})).toBeVisible();await expect(page.getByText("Backbeat",{exact:true})).toBeVisible();const transport=page.getByRole("region",{name:"Waveform and transport"});const before=Number(await transport.getAttribute("data-source-time-us"));await page.keyboard.press("Space");await expect(page.getByRole("button",{name:"Pause",exact:true})).toHaveAttribute("aria-pressed","true");await expect.poll(async()=>Number(await transport.getAttribute("data-source-time-us")),{timeout:5_000}).toBeGreaterThan(before+250_000);await page.keyboard.press("Space");await expect(page.getByRole("button",{name:"Play",exact:true})).toHaveAttribute("aria-pressed","false");expect(errors).toEqual([])});

test("authorized YouTube acquisition exposes server and browser separation choices",async({page})=>{let suppliedKey="";await page.addInitScript(()=>sessionStorage.setItem("atarang.cloud.configuration",JSON.stringify({origin:"http://127.0.0.1:4173",deploymentKey:"a".repeat(64)})));await page.route("http://127.0.0.1:4173/api/v1/capabilities",async route=>{suppliedKey=await route.request().headerValue("X-Atarang-Key")??"";await route.fulfill({json:{cloudEnabled:true,youtubeEnabled:true}})});await page.goto("/library");await expect(page.getByRole("heading",{name:"Fetch from YouTube"})).toBeVisible();await expect(page.getByLabel("YouTube URL")).toBeVisible();const submit=page.getByRole("button",{name:"Fetch and separate"});await page.getByLabel("YouTube URL").fill("https://www.youtube.com/watch?v=Ajxn0PKbv7I");await expect(submit).toBeDisabled();await page.getByLabel("I confirm I am authorized to download and process this content.").check();await expect(submit).toBeEnabled();await page.getByLabel(/Fetch only; separate in this browser/).check();await expect(page.getByRole("button",{name:"Fetch to browser"})).toBeEnabled();expect(suppliedKey).toBe("a".repeat(64))});

test("YouTube submission works when randomUUID is unavailable on an HTTP origin",async({page})=>{let idempotencyKey="";await page.addInitScript(()=>{Object.defineProperty(crypto,"randomUUID",{value:undefined,configurable:true});sessionStorage.setItem("atarang.cloud.configuration",JSON.stringify({origin:"http://127.0.0.1:4173",deploymentKey:"a".repeat(64)}))});await page.route("http://127.0.0.1:4173/api/v1/capabilities",route=>route.fulfill({json:{cloudEnabled:true,youtubeEnabled:true}}));await page.route("http://127.0.0.1:4173/api/v1/jobs",async route=>{idempotencyKey=await route.request().headerValue("Idempotency-Key")??"";await route.fulfill({json:{jobId:"019fef4f-9c77-7a3f-94ca-ef4214a806c1",capabilityToken:"canary-capability",state:"acquiring_youtube"}})});await page.route("http://127.0.0.1:4173/api/v1/jobs/019fef4f-9c77-7a3f-94ca-ef4214a806c1",route=>route.fulfill({json:{state:"failed",stage:"failed",progress:.1}}));await page.goto("/library");await page.getByLabel("YouTube URL").fill("https://www.youtube.com/watch?v=Ajxn0PKbv7I");await page.getByLabel("I confirm I am authorized to download and process this content.").check();await page.getByRole("button",{name:"Fetch and separate"}).click();await expect(page.getByRole("alert")).toContainText("failed");expect(idempotencyKey).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/)});

test("supported compact layout has no horizontal overflow and keeps transport visible",async({page,isMobile})=>{test.skip(!isMobile,"compact layout project only");await page.goto("/studio");const layout=await page.evaluate(()=>({viewport:innerWidth,scrollWidth:document.documentElement.scrollWidth,transport:document.querySelector('[aria-label="Waveform and transport"]')?.getBoundingClientRect().bottom}));expect(layout.scrollWidth).toBe(layout.viewport);expect(layout.transport).toBeLessThanOrEqual(await page.evaluate(()=>innerHeight));await expect(page.getByRole("tab",{name:"Takes"})).toBeVisible()});

test("cloud operator configuration is session-only and precache excludes private routes",async({page,request})=>{await page.route("http://127.0.0.1:4173/api/v1/capabilities",route=>route.fulfill({json:{cloudEnabled:true}}));await page.goto("/settings");await page.getByLabel("Server origin").fill("http://127.0.0.1:4173/path");await page.getByLabel("Deployment key").fill("a".repeat(64));await page.getByRole("button",{name:"Save and test"}).click();await expect(page.getByText("Server capability verified for this session.")).toBeVisible();const stored=await page.evaluate(()=>sessionStorage.getItem("atarang.cloud.configuration"));expect(stored).toContain("http://127.0.0.1:4173");expect(stored).toContain("a".repeat(64));const precache=await request.get("/precache.json");expect(precache.ok()).toBeTruthy();const paths=await precache.json() as string[];expect(paths.some(path=>path.endsWith(".map")||path.startsWith("/api/")||path.startsWith("/models/"))).toBeFalsy()});

test("a rejected deployment key is not saved",async({page})=>{await page.route("http://127.0.0.1:4173/api/v1/capabilities",route=>route.fulfill({status:401,json:{error:{code:"invalid_source"}}}));await page.goto("/settings");await page.getByLabel("Server origin").fill("http://127.0.0.1:4173");await page.getByLabel("Deployment key").fill("random-key");await page.getByRole("button",{name:"Save and test"}).click();await expect(page.getByText(/Deployment key rejected/)).toBeVisible();expect(await page.evaluate(()=>sessionStorage.getItem("atarang.cloud.configuration"))).toBeNull()});

test("Signalsmith worklet loads from its same-origin runtime module",async({page})=>{const cspErrors:string[]=[];page.on("console",message=>{if(message.type()==="error"&&message.text().includes("Content Security Policy"))cspErrors.push(message.text())});await page.goto("/studio");await page.getByRole("button",{name:"Play",exact:true}).click();const result=await page.evaluate(async()=>{const paths=await fetch("/precache.json").then(response=>response.json()) as string[];const moduleUrl=paths.find(path=>path.includes("SignalsmithStretch"));if(!moduleUrl)return"missing";const module=await import(moduleUrl);module.default.moduleUrl=moduleUrl;const context=new AudioContext();const node=await module.default(context,{numberOfInputs:1,numberOfOutputs:1,outputChannelCount:[2]});node.disconnect();await context.close();return"loaded"});expect(result).toBe("loaded");expect(cspErrors).toEqual([])});

test("separation chooser exposes only qualified local compute and never implies an upload",async({page})=>{const errors:string[]=[];page.on("console",message=>{if(message.type()==="error")errors.push(message.text())});page.on("pageerror",error=>errors.push(error.message));await page.goto("/library");await page.getByLabel("Choose audio to import").setInputFiles({name:"route-check.wav",mimeType:"audio/wav",buffer:silentWav()});await expect(page).toHaveURL(/\/studio\//);await expect(page.getByText("Route Check",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Open separation options"})).toBeVisible();await page.getByRole("button",{name:"Open separation options"}).click();const dialog=page.getByRole("dialog",{name:"Separate this song"});await expect(dialog).toBeVisible();await expect(dialog.getByText("Local on this device")).toBeVisible();await expect(dialog.getByRole("button",{name:"Not qualified"})).toBeDisabled();await expect(dialog.getByText("Audio is never uploaded automatically.")).toBeVisible();await expect(dialog.getByRole("button",{name:"Import package"})).toBeEnabled();expect(errors).toEqual([])});
