import {AudioSample,AudioSampleSource,BufferTarget,Mp3OutputFormat,Output,Quality} from "mediabunny";
import {registerMp3Encoder} from "@mediabunny/mp3-encoder";
import {IncrementalSha256} from "../storage/sha256";

// No browser ships an MP3 encoder in WebCodecs, so exports go through LAME.
// Registration is bookkeeping and the wasm only instantiates once a track asks
// for it, but its bytes ride along in this worker, which recording loads too.
// ponytail: worth its own worker entry only if record start starts feeling it.
registerMp3Encoder();

interface RecordingRing{sab:SharedArrayBuffer;capacityFrames:number}
interface StartMessage{type:"recording/start";requestId:string;operationId:string;sampleRate:number;mic:RecordingRing;backing:RecordingRing}
interface StopMessage{type:"recording/stop";requestId:string}
interface ExportMessage{type:"export/mix";format:"wav"|"mp3";requestId:string;performanceId:string;exportId:string;sampleRate:number;micPath:string;backingPath:string;trimStartFrame:number;trimEndFrame:number;fadeInFrames:number;fadeOutFrames:number;inputOffsetFrames:number;micGain:number;backingGain:number}
type SyncHandle={write(data:BufferSource,options?:{at?:number}):number;read(data:BufferSource,options?:{at?:number}):number;truncate(size:number):void;flush():void;close():void}
type Writable={handle:SyncHandle;position:number;frames:number}

let active:null|{requestId:string;operationId:string;sampleRate:number;mic:RecordingRing;backing:RecordingRing;micFile:Writable;backingFile:Writable;timer:number}=null;
const directory=async(root:FileSystemDirectoryHandle,parts:string[])=>{let value=root;for(const part of parts)value=await value.getDirectoryHandle(part,{create:true});return value};
const syncHandle=async(file:FileSystemFileHandle)=>await (file as FileSystemFileHandle&{createSyncAccessHandle():Promise<SyncHandle>}).createSyncAccessHandle();
const wavHeader=(sampleRate:number,frames:number)=>{const buffer=new ArrayBuffer(44),view=new DataView(buffer),text=(offset:number,value:string)=>{for(let i=0;i<value.length;i++)view.setUint8(offset+i,value.charCodeAt(i))},bytes=frames*4;text(0,"RIFF");view.setUint32(4,36+bytes,true);text(8,"WAVE");text(12,"fmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,2,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*4,true);view.setUint16(32,4,true);view.setUint16(34,16,true);text(36,"data");view.setUint32(40,bytes,true);return new Uint8Array(buffer)};

function drain(ring:RecordingRing,target:Writable){const header=new Int32Array(ring.sab,0,8),samples=new Float32Array(ring.sab,32),available=Atomics.load(header,2);if(!available)return;const read=Atomics.load(header,1),first=Math.min(available,ring.capacityFrames-read),second=available-first,pcm=new Int16Array(available*2);for(let frame=0;frame<available;frame++){const source=(read+frame)%ring.capacityFrames;pcm[frame*2]=Math.round(Math.max(-1,Math.min(1,samples[source*2]!))*32767);pcm[frame*2+1]=Math.round(Math.max(-1,Math.min(1,samples[source*2+1]!))*32767)}target.handle.write(pcm,{at:target.position});target.position+=pcm.byteLength;target.frames+=available;Atomics.store(header,1,(read+first+second)%ring.capacityFrames);Atomics.sub(header,2,available)}
function pump(){if(!active)return;drain(active.mic,active.micFile);drain(active.backing,active.backingFile);if(Atomics.load(new Int32Array(active.mic.sab,0,8),4)||Atomics.load(new Int32Array(active.backing.sab,0,8),4)){void finish("recording_overflow")}}
async function publishAsset(root:FileSystemDirectoryHandle,sourcePath:string,sourceHandle:FileSystemFileHandle){const file=await sourceHandle.getFile(),hash=new IncrementalSha256();for await(const chunk of file.stream() as unknown as AsyncIterable<Uint8Array>)hash.update(chunk);const sha256=hash.digestHex(),destinationDirectory=await directory(root,["blobs","sha256",sha256.slice(0,2)]),destination=await destinationDirectory.getFileHandle(sha256,{create:true}),destinationSync=await syncHandle(destination);destinationSync.truncate(0);let position=0;for await(const chunk of file.stream() as unknown as AsyncIterable<Uint8Array>){destinationSync.write(chunk,{at:position});position+=chunk.byteLength}destinationSync.flush();destinationSync.close();return{sha256,blobId:`sha256:${sha256}`,opfsPath:`/blobs/sha256/${sha256.slice(0,2)}/${sha256}`,byteLength:file.size,mediaType:"audio/wav",sourcePath}}
async function finish(error?:string){const session=active;if(!session)return;active=null;clearInterval(session.timer);drain(session.mic,session.micFile);drain(session.backing,session.backingFile);const overflow=Atomics.load(new Int32Array(session.mic.sab,0,8),4)||Atomics.load(new Int32Array(session.backing.sab,0,8),4);if(error||overflow||session.micFile.frames!==session.backingFile.frames||session.micFile.frames<128){session.micFile.handle.close();session.backingFile.handle.close();self.postMessage({type:"recording/error",requestId:session.requestId,code:error??(overflow?"recording_overflow":"recording_discontinuity")});return}for(const file of [session.micFile,session.backingFile]){file.handle.write(wavHeader(session.sampleRate,file.frames),{at:0});file.handle.truncate(file.position);file.handle.flush();file.handle.close()}const root=await navigator.storage.getDirectory(),staging=await directory(root,["staging",session.operationId]),micHandle=await staging.getFileHandle("mic.wav"),backingHandle=await staging.getFileHandle("backing.wav"),mic=await publishAsset(root,`/staging/${session.operationId}/mic.wav`,micHandle),backing=await publishAsset(root,`/staging/${session.operationId}/backing.wav`,backingHandle);await (await root.getDirectoryHandle("staging")).removeEntry(session.operationId,{recursive:true});self.postMessage({type:"recording/complete",requestId:session.requestId,sampleRate:session.sampleRate,durationFrames:session.micFile.frames,mic,backing})}
async function fileHandleForPath(root:FileSystemDirectoryHandle,path:string){const parts=path.split("/").filter(Boolean),name=parts.pop();if(!name)throw new Error("invalid_export_path");return(await directory(root,parts)).getFileHandle(name)}
// One mix, two sinks: MP3 for anything the singer keeps, PCM for the in-app
// preview, which A/Bs against the backing track and so cannot afford the
// encoder's frame padding shifting the take against its reference.
async function exportMix(data:ExportMessage){const mp3=data.format==="mp3",root=await navigator.storage.getDirectory(),mic=await syncHandle(await fileHandleForPath(root,data.micPath)),backing=await syncHandle(await fileHandleForPath(root,data.backingPath)),destinationDirectory=await directory(root,["exports",data.performanceId,data.exportId]),destinationFile=await destinationDirectory.getFileHandle(`mix.${data.format}`,{create:true}),destination=await syncHandle(destinationFile),frames=Math.max(0,data.trimEndFrame-data.trimStartFrame);const target=mp3?new BufferTarget():null,output=target?new Output({format:new Mp3OutputFormat(),target}):null,encoded=output?new AudioSampleSource({codec:"mp3",quality:new Quality("medium")}):null;if(output&&encoded){output.addAudioTrack(encoded);await output.start()}destination.truncate(0);if(!mp3)destination.write(new Uint8Array(44),{at:0});let written=0;const chunkFrames=4096;while(written<frames){const count=Math.min(chunkFrames,frames-written),micPcm=new Int16Array(count*2),backingPcm=new Int16Array(count*2),sourceFrame=data.trimStartFrame+written,micFrame=sourceFrame+data.inputOffsetFrames;if(micFrame>=0)mic.read(micPcm,{at:44+micFrame*4});backing.read(backingPcm,{at:44+sourceFrame*4});const mixed=new Float32Array(count*2);for(let frame=0;frame<count;frame++){const absolute=written+frame,fadeIn=data.fadeInFrames?Math.min(1,absolute/data.fadeInFrames):1,remaining=frames-1-absolute,fadeOut=data.fadeOutFrames?Math.min(1,remaining/data.fadeOutFrames):1,gain=Math.min(fadeIn,fadeOut);for(let channel=0;channel<2;channel++){const index=frame*2;const value=(micPcm[index+channel]!*data.micGain+backingPcm[index+channel]!*data.backingGain)*gain;mixed[index+channel]=Math.max(-1,Math.min(1,value/32768))}}if(encoded){const sample=new AudioSample({data:mixed,format:"f32",numberOfChannels:2,sampleRate:data.sampleRate,timestamp:written/data.sampleRate});await encoded.add(sample);sample.close()}else{const pcm=new Int16Array(count*2);for(let index=0;index<pcm.length;index++)pcm[index]=Math.round(mixed[index]!*32767);destination.write(pcm,{at:44+written*4})}written+=count}mic.close();backing.close();let byteLength=44+frames*4;if(output&&target){await output.finalize();const bytes=new Uint8Array(target.buffer!);destination.write(bytes,{at:0});byteLength=bytes.byteLength}else{destination.write(wavHeader(data.sampleRate,frames),{at:0})}destination.truncate(byteLength);destination.flush();destination.close();self.postMessage({type:"export/complete",requestId:data.requestId,path:`/exports/${data.performanceId}/${data.exportId}/mix.${data.format}`,byteLength,durationFrames:frames})}

self.onmessage=({data}:MessageEvent<StartMessage|StopMessage|ExportMessage>)=>{void(async()=>{if(data.type==="recording/start"){if(active)throw new Error("recording_busy");const root=await navigator.storage.getDirectory(),staging=await directory(root,["staging",data.operationId]),mic=await staging.getFileHandle("mic.wav",{create:true}),backing=await staging.getFileHandle("backing.wav",{create:true}),micSync=await syncHandle(mic),backingSync=await syncHandle(backing);micSync.truncate(0);backingSync.truncate(0);micSync.write(new Uint8Array(44),{at:0});backingSync.write(new Uint8Array(44),{at:0});active={...data,micFile:{handle:micSync,position:44,frames:0},backingFile:{handle:backingSync,position:44,frames:0},timer:setInterval(pump,20) as unknown as number};self.postMessage({type:"recording/ready",requestId:data.requestId})}else if(data.type==="recording/stop")await finish();else await exportMix(data)})().catch(error=>{self.postMessage({type:data.type.startsWith("export/")?"export/error":"recording/error",requestId:data.requestId,code:error instanceof Error?error.message:"recording_failed"})})};
export{};
