import{assertBeatGrid,assertLyricsDocument,assertPerformanceManifest,assertPracticeState,assertSeparationManifest,assertUserChart,assertUserChord,upgradeUserChart,type UserChartV1}from"@atarang/contracts";
import{database,type AtarangDatabase,type BlobRecord,type OriginalRecord,type PerformanceRecord,type SeparationRecord}from"./database";
import{fileForOpfsPath}from"./opfs";
import{IncrementalSha256}from"./sha256";
import{createStoredZip,readStoredZip}from"./zip";
import{uuidV7}from"./ids";
import{notifyLibraryChanged}from"./repositories";

interface BackupAsset{entryName:string;blobId:string;sha256:string;byteLength:number;mediaType:string}
interface BackupManifest{schema:"atarang.backup/1";backupId:string;createdAt:string;includeMedia:boolean;records:{originals:OriginalRecord[];separations:SeparationRecord[];performances:PerformanceRecord[];practice:AtarangDatabase["practice"]["value"][];lyrics:AtarangDatabase["lyrics"]["value"][];charts:AtarangDatabase["charts"]["value"][];userChords?:AtarangDatabase["userChords"]["value"][];beats:AtarangDatabase["beats"]["value"][]};assets:BackupAsset[]}
async function sha(blob:Blob){const hash=new IncrementalSha256();for await(const chunk of blob.stream() as unknown as AsyncIterable<Uint8Array>)hash.update(chunk);return hash.digestHex()}
async function createBackup(includeMedia=true){const db=await database,[originals,separations,performances,practice,lyrics,charts,userChords,beats]=await Promise.all([db.getAll("originals"),db.getAll("separations"),db.getAll("performances"),db.getAll("practice"),db.getAll("lyrics"),db.getAll("charts"),db.getAll("userChords"),db.getAll("beats")]);const wanted=new Set<string>();for(const take of performances){assertPerformanceManifest(take.manifest);wanted.add(take.manifest.mic.blobId);wanted.add(take.manifest.backing.blobId)}if(includeMedia){for(const original of originals)wanted.add(original.blobId);for(const separation of separations)for(const blobId of Object.values(separation.bindings))wanted.add(blobId)}const assets:BackupAsset[]=[],entries:{name:string;blob:Blob}[]=[];for(const blobId of wanted){const record=await db.get("blobs",blobId);if(!record)throw new Error("result_integrity_failed");const file=await fileForOpfsPath(record.opfsPath);if(file.size!==record.byteLength||await sha(file)!==record.sha256)throw new Error("result_integrity_failed");const entryName=`assets/${record.sha256}`;assets.push({entryName,blobId,sha256:record.sha256,byteLength:record.byteLength,mediaType:record.mediaType});entries.push({name:entryName,blob:file})}for(const value of practice)assertPracticeState(value.document);for(const value of lyrics)assertLyricsDocument(value.document);
// Charts are only rewritten into the current shape when the user edits one, so
// the store still holds pre-levels charts long after the upgrade. Validating
// those as-is would fail the whole backup for exactly the person most likely to
// be taking one.
for(const value of charts){value.document=upgradeUserChart(value.document) as UserChartV1;assertUserChart(value.document)}for(const value of userChords)assertUserChord(value.document);for(const value of beats)assertBeatGrid(value.document);const manifest:BackupManifest={schema:"atarang.backup/1",backupId:uuidV7(),createdAt:new Date().toISOString(),includeMedia,records:{originals:includeMedia?originals:[],separations:includeMedia?separations:[],performances,practice,lyrics,charts,userChords,beats},assets},manifestBlob=new Blob([JSON.stringify(manifest)],{type:"application/json"});return createStoredZip([{name:"manifest.json",blob:manifestBlob},...entries])}
export async function downloadBackup(includeMedia=true){const archive=await createBackup(includeMedia),url=URL.createObjectURL(archive),anchor=document.createElement("a");anchor.href=url;anchor.download=`atarang-${new Date().toISOString().slice(0,10)}.atarang-backup.zip`;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function writeAsset(asset:BackupAsset,blob:Blob){const root=await navigator.storage.getDirectory(),directory=await root.getDirectoryHandle("blobs",{create:true}),hashDirectory=await directory.getDirectoryHandle("sha256",{create:true}),prefix=await hashDirectory.getDirectoryHandle(asset.sha256.slice(0,2),{create:true}),handle=await prefix.getFileHandle(asset.sha256,{create:true}),writable=await handle.createWritable({keepExistingData:false});for await(const chunk of blob.stream() as unknown as AsyncIterable<Uint8Array>)await writable.write(new Uint8Array(chunk).buffer as ArrayBuffer);await writable.close()}
export async function restoreBackup(file:Blob){const entries=await readStoredZip(file),manifestBlob=entries.get("manifest.json");if(!manifestBlob)throw new Error("invalid_backup_manifest");const manifest=JSON.parse(await manifestBlob.text())as BackupManifest;if(manifest.schema!=="atarang.backup/1"||!Array.isArray(manifest.assets)||!manifest.records)throw new Error("invalid_backup_manifest");for(const record of manifest.records.separations)assertSeparationManifest(record.manifest);for(const record of manifest.records.performances)assertPerformanceManifest(record.manifest);for(const record of manifest.records.practice)assertPracticeState(record.document);for(const record of manifest.records.lyrics)assertLyricsDocument(record.document);// Upgraded in place, so a backup written before simplification had levels
// restores as a chart this build can read rather than failing the whole file.
for(const record of manifest.records.charts){record.document=upgradeUserChart(record.document) as UserChartV1;assertUserChart(record.document)}const userChords=manifest.records.userChords??[];for(const record of userChords)assertUserChord(record.document);const beatRecords=manifest.records.beats??[];for(const record of beatRecords)assertBeatGrid(record.document);for(const asset of manifest.assets){const blob=entries.get(asset.entryName);if(!blob||blob.size!==asset.byteLength||await sha(blob)!==asset.sha256||asset.blobId!==`sha256:${asset.sha256}`)throw new Error("backup_integrity_failed")}for(const asset of manifest.assets)await writeAsset(asset,entries.get(asset.entryName)!);const db=await database,transaction=db.transaction(["originals","separations","performances","practice","lyrics","charts","userChords","beats","blobs"],"readwrite"),references=new Map<string,number>();const add=(id:string)=>references.set(id,(references.get(id)??0)+1);for(const value of manifest.records.originals)add(value.blobId);for(const value of manifest.records.separations)for(const id of Object.values(value.bindings))add(id);for(const value of manifest.records.performances){add(value.manifest.mic.blobId);add(value.manifest.backing.blobId)}for(const asset of manifest.assets){const existing=await transaction.objectStore("blobs").get(asset.blobId),now=new Date().toISOString(),record:BlobRecord={id:asset.blobId,schemaVersion:1,createdAt:existing?.createdAt??now,updatedAt:now,sha256:asset.sha256,byteLength:asset.byteLength,mediaType:asset.mediaType,opfsPath:`/blobs/sha256/${asset.sha256.slice(0,2)}/${asset.sha256}`,referenceCount:Math.max(existing?.referenceCount??0,references.get(asset.blobId)??1)};await transaction.objectStore("blobs").put(record)}for(const value of manifest.records.originals)await transaction.objectStore("originals").put(value);for(const value of manifest.records.separations)await transaction.objectStore("separations").put(value);for(const value of manifest.records.performances)await transaction.objectStore("performances").put(value);for(const value of manifest.records.practice)await transaction.objectStore("practice").put(value);for(const value of manifest.records.lyrics)await transaction.objectStore("lyrics").put(value);for(const value of manifest.records.charts)await transaction.objectStore("charts").put(value);for(const value of userChords)await transaction.objectStore("userChords").put(value);for(const value of beatRecords)await transaction.objectStore("beats").put(value);await transaction.done;notifyLibraryChanged();return{backupId:manifest.backupId,originals:manifest.records.originals.length,performances:manifest.records.performances.length,userRecords:manifest.records.practice.length+manifest.records.lyrics.length+manifest.records.charts.length+userChords.length+beatRecords.length}}
